/**
 * Иконки админки — lucide-react под именами из прототипа
 * (apps/claudeDesign/scripts/icons.jsx). Стиль Lucide/Feather, stroke 2 —
 * совпадает с исходными SVG. Централизованный реэкспорт, чтобы страницы
 * импортировали из одного места.
 */
import {
  Search,
  Building2,
  Home,
  Check,
  User,
  UserCheck,
  Sparkles,
  List,
  SlidersHorizontal,
  Bell,
  Menu,
  Mail,
  Phone,
  CalendarDays,
  Clock,
  Flag,
  LogOut,
  X,
  Plus,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Send,
  MessageSquare,
  Megaphone,
  TriangleAlert,
  ListChecks,
  Pencil,
  FileText,
  ShieldCheck,
  type LucideIcon,
} from 'lucide-react';

export const IC = {
  Search,
  Building: Building2,
  Home,
  Check,
  User,
  UserCheck,
  Sparkle: Sparkles,
  ListIcon: List,
  Sliders: SlidersHorizontal,
  Bell,
  Menu,
  Mail,
  Phone,
  Calendar: CalendarDays,
  Clock,
  Flag,
  LogOut,
  X,
  Plus,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Send,
  MessageSquare,
  Megaphone,
  Alert: TriangleAlert,
  Checklist: ListChecks,
  Edit: Pencil,
  FileText,
  ShieldCheck,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof IC;
export type { LucideIcon };
