-- listing_media.storage_key: стабильный S3/R2 object key файла (ADR-0086).
--
-- Прежде в `url` хранился целиком presigned GET URL с TTL = S3_SIGNED_URL_TTL
-- (по умолчанию 3600s). URL сохранялся ОДИН РАЗ при загрузке и отдавался как есть
-- во всех read-path. Через час подпись истекала → R2/S3 отвечал
-- `403 ExpiredRequest` на каждую <img>, и фото "пропадали" в детали объявления,
-- в очереди модерации и в форме редактирования одновременно.
--
-- Теперь в БД лежит стабильный key, а presigned URL генерируется на лету ПРИ
-- КАЖДОМ ЧТЕНИИ (UploadsService.resolveMediaUrl) — протухание невозможно.
--
-- Колонка nullable и БЕЗ бэкфилла намеренно: уже загруженные строки имеют
-- storage_key = NULL, и read-path подписывает их через extractKey(url)-фолбэк
-- (ключ восстанавливается из сохранённого URL). Это безопасно кросс-окружениями
-- (bucket/endpoint различаются dev/prod), тогда как SQL-бэкфилл захардкодил бы
-- имя бакета. Новые загрузки заполняют storage_key явно.
ALTER TABLE "listing_media" ADD COLUMN "storage_key" TEXT;
